FROM python:3.6.5-slim

# install environment dependencies
RUN apt-get update -yqq \
	&& apt-get install -yqq --no-install-recommends \
		netcat \
	&& apt-get -q clean



# add requirements
COPY ./requirements.txt /project/requirements.txt

# set working directory to /project/
WORKDIR /project/

# install requirements
RUN pip install -r requirements.txt


